"""followers

Revision ID: 82616278fe9f
Revises: a174ce7caaa7
Create Date: 2020-09-06 14:52:58.380054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82616278fe9f'
down_revision = 'a174ce7caaa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
